#!/usr/bin/env bash
# health_check.sh – simple health‑check for a server running Docker, systemd services and network sockets
# Generated by local LLM agent (GPT-OSS 120B)
# -------------------------------------------------------------------------
# Exit on any unexpected error (but we handle most errors ourselves)
set -euo pipefail

# -------------------------------------------------------------------------
# Helper functions
# -------------------------------------------------------------------------
log()   { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }
warn()  { log "WARN: $*"; }
error() { log "ERROR: $*"; }

# -------------------------------------------------------------------------
# 1. Docker containers – list and verify they are running
# -------------------------------------------------------------------------
log "Checking Docker containers …"
if ! command -v docker >/dev/null 2>&1; then
    warn "Docker CLI not found – skipping Docker checks."
else
    # Get container names and status (running / exited / …)
    mapfile -t containers < <(docker ps --format '{{.Names}} {{.Status}}')
    if [[ ${#containers[@]} -eq 0 ]]; then
        warn "No Docker containers are running."
    else
        for line in "${containers[@]}"; do
            name=$(awk '{print $1}' <<<"$line")
            status=$(awk '{$1=""; print $0}' <<<"$line" | xargs)
            if [[ $status != Up* ]]; then
                warn "Container '$name' is NOT running (status: $status)."
            else
                log "Container '$name' is healthy ($status)."
            fi
        done
    fi
fi

# -------------------------------------------------------------------------
# 2. Systemd services – list a subset of critical services and verify they are active
# -------------------------------------------------------------------------
log "Checking critical systemd services …"
# Define a list of services you consider essential.
critical_services=(
    docker
    sshd
    keepalived
)

for svc in "${critical_services[@]}"; do
    if systemctl is-active --quiet "$svc.service"; then
        log "Service '$svc' is active."
    else
        warn "Service '$svc' is NOT active."
    fi
done

# -------------------------------------------------------------------------
# 3. Listening sockets – verify that expected ports are open
# -------------------------------------------------------------------------
log "Checking listening sockets …"
# Expected ports (protocol:port). Add/remove as needed.
declare -A expected_ports=(
    ["tcp:22"]="sshd"
    ["tcp:80"]="nginx"
    ["tcp:443"]="nginx"
)

# Get current listening sockets
listening_ports=$(ss -tuln | awk 'NR>1 {print $1, $5}')

check_port() {
    local proto=$1 port=$2
    echo "$listening_ports" | grep -q "$proto.*:$port\$" && return 0
    echo "$listening_ports" | grep -q "$proto.*:$port " && return 0
    return 1
}

for key in "${!expected_ports[@]}"; do
    IFS=':' read -r proto port <<<"$key"
    if check_port "$proto" "$port"; then
        log "Listening $proto port $port (${expected_ports[$key]})."
    else
        warn "Expected $proto port $port (${expected_ports[$key]}) is NOT listening."
    fi
done

# -------------------------------------------------------------------------
# 4. Resource usage
# -------------------------------------------------------------------------
log "Checking resource usage …"
disk_usage=$(df -h / | awk 'NR==2 {print $5}' | tr -d '%')
mem_usage=$(free | awk '/Mem:/ {printf "%.0f", $3/$2 * 100}')
load_avg=$(uptime | awk -F'load average:' '{print $2}' | awk -F',' '{print $1}' | xargs)

log "Disk usage: ${disk_usage}%"
log "Memory usage: ${mem_usage}%"
log "Load average (1m): ${load_avg}"

if [[ $disk_usage -gt 90 ]]; then
    warn "Disk usage is critical (${disk_usage}%)"
elif [[ $disk_usage -gt 80 ]]; then
    warn "Disk usage is high (${disk_usage}%)"
fi

if [[ $mem_usage -gt 90 ]]; then
    warn "Memory usage is critical (${mem_usage}%)"
elif [[ $mem_usage -gt 80 ]]; then
    warn "Memory usage is high (${mem_usage}%)"
fi

# -------------------------------------------------------------------------
# 5. Summary
# -------------------------------------------------------------------------
log "Health-check completed."
